# Generated by Django 5.1.1 on 2024-10-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_image_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
    ]
