# Generated by Django 5.1.1 on 2024-10-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_discription_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='discription',
        ),
    ]
