# Generated by Django 5.1.1 on 2024-10-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('SSLcommerz', 'SSLcommerz')], default='Cash on Delivery', max_length=20),
        ),
    ]
