# Generated by Django 5.1.1 on 2024-10-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Payment',
            new_name='payment',
        ),
    ]
